version: "3"
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ../backend/pg:/docker-entrypoint-initdb.d
  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
    ports:
      - "80:8000"
